name: Latest blog post workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blogs:
    name: Update Blogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update the blogs
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://thedevden.hashnode.dev/rss.xml"
